feat: search text from selection
kbysiec/vscode-search-everywhere pull request #33
Opened 2022-11-27 02:33 UTC by mahaker

close https://github.com/kbysiec/vscode-search-everywhere/issues/31
Provide a more similar feel to Intellij's IDE.

2022-11-27 02:38 UTC, mahaker commented on src/test/testSetup/controller.testSetup.ts
> +          },
Could not stub `vscode.window.activeTextEditor`.
So I could not write a test when `vscode.window.activeTextEditor` is undefined 😭 

At that time I had to write code like this.
```js
{
  object: vscode,
  method: "window",
  returns: ({ activeTextEditor: undefined })
},
```

2023-02-01 10:57 UTC, kbysiec requested changes
Hi @mahaker,

First of all thank you for your PR and apologies for such a delay in reviewing and responding. I had difficult period with no time for side projects at all.

I have reviewied your solution and changed in some places because I would like to be consistent with the whole codebase. 
Additionally, I can see the one think to improve - if you open the quickPick with text selected and debounce enabled, there is a blinking of itemsList on open. But don't worry I have an idea how to fix it so just after merging your PR I will add some improvements from my side and release the new version.

Thanks one more time for your help.
In case of any questions, let me know.

Kamil

2023-02-01 10:57 UTC, kbysiec commented on src/controller.ts
> +
```suggestion
function shouldSearchSelection(editor: vscode.TextEditor | undefined) {
  return quickPick.isInitialized() && fetchShouldSearchSelection() && !!editor;
}
```

2023-02-01 10:57 UTC, kbysiec commented on src/controller.ts
> +  }
```suggestion

  const activeEditorOrUndefined = vscode.window.activeTextEditor;
  
  if (controller.shouldSearchSelection(activeEditorOrUndefined)) {
    const activeEditor = activeEditorOrUndefined as vscode.TextEditor;
    
    const { start, end } = activeEditor.selection;
    quickPick.setText(editor.document.getText(new vscode.Range(start, end)));
  }
```

ShouldSearchSelection method be invoked from controller due to necessity to mock it in test correctly.

2023-02-01 10:57 UTC, kbysiec commented on src/controller.ts
> +  shouldQuickPickOpenFromSelection,
```suggestion
  shouldSearchSelection,
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/util/mockFactory.ts
> +      shouldQuickPickOpenFromSelection: true,
```suggestion
      shouldSearchSelection: true,
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/config.test.ts
> +  describe("fetchShouldQuickPickOpenFromSelection", () => {
```suggestion
  describe("fetchShouldSearchSelection", () => {
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/config.test.ts
> +      const key = "shouldQuickPickOpenFromSelection";
```suggestion
      const key = "fetchShouldSearchSelection";
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/config.test.ts
> +        config.fetchShouldQuickPickOpenFromSelection(),
```suggestion
        config.fetchShouldSearchSelection(),
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/controller.test.ts
> +    });
```suggestion

    it(`10: should set selected text as quickPick text if shouldSearchSelection
      returns true`, async () => {
      const [setTextStub] = setups.search10();
      await controller.search();

      assert.equal(setTextStub.calledWith("test text"), true);
    });
    
    it(`11: should not invoke quickPick.setText method if shouldSearchSelection
      returns false`, async () => {
      const [setTextStub] = setups.search11();
      await controller.search();

      assert.equal(setTextStub.calledOnce, false);
    });
```

I would suggest to test only whether based on shouldSearchSelection method and shouldSearchSelection method test separately.

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/controller.test.ts
> +  describe("shouldQuickPickOpenFromSelection", () => {
```suggestion
  describe("shouldSearchSelection", () => {
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/controller.test.ts
> +      setups.shouldQuickPickOpenFromSelection1();
```suggestion
      setups.shouldSearchSelection1();
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/controller.test.ts
> +      assert.equal(controller.shouldQuickPickOpenFromSelection(), false);
```suggestion
      assert.equal(controller.shouldSearchSelection(), false);
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/controller.test.ts
> +    it("2: should return false if fetchShouldQuickPickOpenFromSelection method returns false", () => {
```suggestion
    it("2: should return false if fetchShouldSearchSelection method returns false", () => {
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/controller.test.ts
> +      setups.shouldQuickPickOpenFromSelection2();
```suggestion
      setups.shouldSearchSelection2();
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/controller.test.ts
> +      assert.equal(controller.shouldQuickPickOpenFromSelection(), false);
```suggestion
      assert.equal(controller.shouldSearchSelection(), false);
```

2023-02-01 10:57 UTC, kbysiec commented on src/test/test/controller.test.ts
> +
```suggestion
    it("3: should return false if editor doesn't exist", () => {
      const editor = setups.shouldSearchSelection3();
      assert.equal(controller.shouldSearchSelection(editor), false);
    });

    it(`4: should return true if quickPick is initialized,
      fetchShouldSearchSelection returns false and editor exists`, () => {
      const editor = setups.shouldSearchSelection4();
      assert.equal(controller.shouldSearchSelection(editor), true);
    });
  });

```

Add one more test to verify if active editor exists.

2023-02-01 10:57 UTC, kbysiec commented on src/test/testSetup/controller.testSetup.ts
> +    },
```suggestion
    //above getTestSetups
    function stubComponentsForShouldSearchSelection(
      sandbox: sinon.SinonSandbox,
      returnsValues: { [key: string]: any }
    ) {
      return stubMultiple(
        [
          {
            object: quickPick,
            method: "isInitialized",
            returns: returnsValues.isInitialized,
          },
          {
            object: config,
            method: "fetchShouldSearchSelection",
            returns: returnsValues.fetchShouldSearchSelection,
          },
        ],
        sandbox
      );
    }

    shouldSearchSelection1: () => {
      stubComponents(sandbox);
      stubComponentsForShouldSearchSelection(sandbox, {
        isInitialized: false,
        fetchShouldSearchSelection: true,
      });
      const editor = getTextEditorStub(true, "test text");

      return editor;
    },
    shouldSearchSelection2: () => {
      stubComponents(sandbox);
      stubComponentsForShouldSearchSelection(sandbox, {
        isInitialized: true,
        fetchShouldSearchSelection: false,
      });
      const editor = getTextEditorStub(true, "test text");

      return editor;
    },
    shouldSearchSelection3: () => {
      stubComponents(sandbox);
      stubComponentsForShouldSearchSelection(sandbox, {
        isInitialized: true,
        fetchShouldSearchSelection: true,
      });
      const editor = undefined;

      return editor;
    },
    shouldSearchSelection4: () => {
      stubComponents(sandbox);
      stubComponentsForShouldSearchSelection(sandbox, {
        isInitialized: true,
        fetchShouldSearchSelection: true,
      });
      const editor = getTextEditorStub(true, "test text");

      return editor;
    },
```

You can find above mock for undefined return for editor.

2023-02-01 10:57 UTC, kbysiec commented on src/test/testSetup/controller.testSetup.ts
> +          },
```suggestion
```

Look at code suggestion in next code block.

2023-02-01 10:57 UTC, kbysiec commented on src/test/testSetup/controller.testSetup.ts
> +    },
```suggestion
      search10: () => {
      stubComponents(sandbox);
      stubComponentsForSearch(sandbox, {
        isInitialized: true,
        shouldIndexOnQuickPickOpen: false,
        shouldLoadDataFromCacheOnQuickPickOpen: false,
        shouldSearchSelection: true,
      });
      const editor = getTextEditorStub(true, "test text");

      return stubMultiple(
        [
          {
            object: quickPick,
            method: "setText",
          },
          {
            object: quickPick,
            method: "loadItems",
          },
          {
            object: quickPick,
            method: "show",
          },
          {
            object: vscode.window,
            method: "activeTextEditor",
            isNotMethod: true,
            returns: editor,
          },
        ],
        sandbox
      );
    },
    search11: () => {
      stubComponents(sandbox);
      stubComponentsForSearch(sandbox, {
        isInitialized: true,
        shouldIndexOnQuickPickOpen: false,
        shouldLoadDataFromCacheOnQuickPickOpen: false,
        shouldSearchSelection: false,
      });

      return stubMultiple(
        [
          {
            object: quickPick,
            method: "setText",
          },
          {
            object: quickPick,
            method: "loadItems",
          },
          {
            object: quickPick,
            method: "show",
          },
        ],
        sandbox
      );
    },
```

2023-02-03 10:16 UTC, mahaker commented
Hi @kbysiec !

Thanks for the very thoughtful review!
I have committed the fixes and would appreciate your confirmation.

Best regards.

2023-02-03 13:46 UTC, merged

2023-02-03 14:18 UTC, kbysiec commented
@mahaker,

thank you for your changes. I have reviewed them, merged and after some improvements on my side released in new version  [v.2.1.0](https://github.com/kbysiec/vscode-search-everywhere/tree/v.2.1.0)